### ISSUE TITLE
EmojiTextView setText crash

### ISSUE THREAD

**Issue by amirghm** [vanniktech/Emoji#260]
Hi in android 7.0+ some crash sent to server because of EmojiTextView setText crash.
I've searched and found nothing, but guess it's related to webview kit on clients.

here is the error:

```
Caused by android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
       at android.webkit.WebView.getFactory(WebView.java:2325)
       at android.webkit.WebView.findAddress(WebView.java:1727)
       at android.text.util.Linkify.gatherMapLinks(Linkify.java:551)
       at android.text.util.Linkify.addLinks(Linkify.java:254)
       at android.widget.TextView.setText(TextView.java:4666)
       at android.widget.TextView.setText(TextView.java:4587)
       at com.vanniktech.emoji.EmojiTextView.setText(Unknown Source:51)
       at android.widget.TextView.(TextView.java:1483)
       at android.widget.TextView.(TextView.java:742)
       at android.support.v7.widget.AppCompatTextView.(Unknown Source:62)
       at android.support.v7.widget.AppCompatTextView.(Unknown Source:58)
       at com.vanniktech.emoji.EmojiTextView.(Unknown Source:21)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
       at ir.digitaldreams.hodhod.ui.adapters.conversations.ConversationAdapter.onCreateViewHolder(Unknown Source:174)
       at ir.digitaldreams.hodhod.ui.adapters.conversations.ConversationAdapter.onCreateViewHolder(Unknown Source:80)
       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(Unknown Source:6367)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(Unknown Source:5555)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5436)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(Unknown Source:2224)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(Unknown Source:1551)
       at android.support.v7.widget.LinearLayoutManager.fill(Unknown Source:1511)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:570)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(Unknown Source:3583)
       at android.support.v7.widget.RecyclerView.dispatchLayout(Unknown Source:3312)
       at android.support.v7.widget.RecyclerView.onLayout(Unknown Source:3844)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:755)
       at android.view.View.layout(View.java:17572)
       at android.view.ViewGroup.layout(ViewGroup.java:5656)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2429)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2149)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1306)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6579)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
       at android.view.Choreographer.doCallbacks(Choreographer.java:683)
       at android.view.Choreographer.doFrame(Choreographer.java:619)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6316)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

```
I've added your library to my app as a module, to add new features.

how can I solve this issue?
this error occurred on samsung device usually.

**Comment by vanniktech** [comment]
I think the underlying issue is in some modifications that Samsung did in their TextView and / or Webview.

If you can prove otherwise, that'd be great.

**Comment by amirghm** [comment]
![image](https://user-images.githubusercontent.com/3845492/36727539-e36bf0ec-1bd2-11e8-9414-3bf6f9d302d1.png)

![image](https://user-images.githubusercontent.com/3845492/36727591-11b6fc80-1bd3-11e8-95c6-fb1230df1b2f.png)


here is fabric info about this crash.
some lge models also have this problem.

and there is a stackoverflow post for this issue:
https://stackoverflow.com/questions/46048912/android-failed-to-load-webview-provider-no-webview-installed

**Comment by amirghm** [comment]
I try to modify setText method like this.
not tested yet for reproduce this exception on our user.
but maybe remove the crash and use built in emoji in these devices

```
 try 
 {
      super.setText(spannableStringBuilder, type);
 }
 catch (Exception e)
 {
      super.setText(rawText,type);
 }
```

**Comment by vanniktech** [comment]
There's also some information about this here - https://github.com/opengapps/aosp_build/issues/89

Seems like an ORM bug to me.

Can you try your workaround and report back whether it helped?

**Comment by amirghm** [comment]
yes sure,
I take screenshot from new version analytics, and send it here for more information.

**Comment by amirghm** [comment]
this approach not working, seems the error come from outside of this thread and catch cannot handle it or maybe the crash also occurs in the catch.
unfortunately, it's a serious bug and I don't know what to do.

**Comment by vanniktech** [comment]
This library can't do anything about it since it's not the cause for this crash. I'd say there are problems with the specific vendor.
