### ISSUE TITLE
Binary XML file line #0: Binary XML file line #0: Error inflating class com.vanniktech.EmojiEditText

### ISSUE THREAD

**Issue by omar-othmann** [vanniktech/Emoji#261]
Libraray version: 0.5.1
Device: Pixel_2_XL_API: 26

Error on EmojiManager:
com.vanniktech.EmojiReplacer.replaceWithImages(android.content.Context, android.text.Spannable, float, float, com.vanniktech.EmojiReplacer)' on a null object reference

xml:
<com.vanniktech.EmojiEditText
            android:id="@+id/input"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentTop="true"
            android:imeOptions="actionSend"
            android:inputType="textCapSentences|textMultiLine"
            android:layout_toLeftOf="@+id/fab"
            android:layout_toStartOf="@+id/fab" />
i have write this onCreate Activity
`EmojiManager.install(new IosEmojiProvider());`

**Comment by omar-othmann** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: d.com.test, PID: 6353
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{d.com.test/com.test.ChatActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.vanniktech.EmojiEditText
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.vanniktech.EmojiEditText
                   Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.vanniktech.EmojiEditText
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.deldram.ChatActivity.onCreate(ChatActivity.java:60)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void del.com.emo.EmojiReplacer.replaceWithImages(android.content.Context, android.text.Spannable, float, float, com.vanniktech.EmojiReplacer)' on a null object reference
                      at com.vanniktech.EmojiManager.replaceWithImages(EmojiManager.java:153)
                      at com.vanniktech.EmojiEditText.onTextChanged(EmojiEditText.java:49)
                      at android.widget.TextView.setText(TextView.java:5396)
                      at android.widget.TextView.setText(TextView.java:5248)
                      at android.widget.EditText.setText(EditText.java:113)
                      at android.widget.TextView.<init>(TextView.java:1624)
                      at android.widget.EditText.<init>(EditText.java:88)
                      at android.widget.EditText.<init>(EditText.java:84)
E/AndroidRuntime:     at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:62)
                      at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:58)
                      at com.vanniktech.EmojiEditText.<init>(EmojiEditText.java:0)
                      	... 30 more

**Comment by vanniktech** [comment]
Seems like there's something wrong with your layout.

**Comment by omar-othmann** [comment]
nope!
its work on default EditText

**Comment by vanniktech** [comment]
Can you try it in the sample app? If it works there there's something wrong in your setup.

**Comment by omar-othmann** [comment]
Ok i try it

**Comment by omar-othmann** [comment]
Its work in the sample app, i check my setup thank you!

**Comment by vanniktech** [comment]
Try installing the provider in your application class instead.

**Comment by omar-othmann** [comment]
i think i need this code on my application:
`public class EmojiApplication extends Application {
  @Override public void onCreate() {
    super.onCreate();

    if (LeakCanary.isInAnalyzerProcess(this)) {
      return;
    }

    AppCompatDelegate.setDefaultNightMode(MODE_NIGHT_AUTO);

    EmojiManager.install(new IosEmojiProvider());

    if (BuildConfig.DEBUG) {
      StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder().detectAll().build());
      StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().detectAll().build());
    }

    LeakCanary.install(this);
  }
}`

**Comment by vanniktech** [comment]
Yeah.

**Comment by vanniktech** [comment]
I'm guessing this is resolved now and can be closed.

**Comment by LiMengyang990726** [comment]
Where is the sample app?

**Comment by adil9d** [comment]
> Where is the sample app?

check this must initialize in manifest
https://www.geeksforgeeks.org/how-to-integrate-emojis-in-an-android-app/
