### ISSUE TITLE
Emoji keyboard is not popping up ?

### ISSUE THREAD

**Issue by drmkraja** [vanniktech/Emoji#457]
Thank you for filing an issue. If this is a bug that you want to report, please take the time to provide some information:

- Version of the library: 0.7.0-SNAPSHOT
- Affected devices: All
- Affected versions: All

Screenshot(s) showing the issue and reprodution steps are appreciated.

----------------------------------------------------------------------

Thanks for the Awesome lib. I tried to run the sample project. It works well. But when I use the same code in my project Emoji keyboard is not popping. I have attached the log cat below. Here is [code from my project](https://gist.github.com/drmkraja/4330c5025cfd9adc986c790814b36f97)... 

**LOGCAT** 

`2020-07-16 19:08:52.179 14499-14499/com.stkyr.stkyrapp E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.vanniktech.emoji.EmojiPopup.start()' on a null object reference
        at com.vanniktech.emoji.EmojiEditText$ForceEmojisOnlyFocusChangeListener.onFocusChange(EmojiEditText.java:123)
        at android.view.View.onFocusChanged(View.java:7276)
        at android.widget.TextView.onFocusChanged(TextView.java:10030)
        at android.view.View.handleFocusGainInternal(View.java:6945)
        at android.view.View.requestFocusNoSearch(View.java:11559)
`

**Comment by vanniktech** [comment]
Seems like a problem with your code if you're getting a NPE.
