### ISSUE TITLE
App crash on EmojiManager.install

### ISSUE THREAD

**Issue by nitishRakuten** [vanniktech/Emoji#498]
- Version of the library: 0.7.0
- Affected devices: AQUOS sense4 lite SH-RM15
- Affected versions: Android 11

Screenshot(s) showing the issue and reprodution steps are appreciated.
----------------------------------------------------------------------

Caused by java.lang.NullPointerException: Attempt to invoke direct method 'void com.vanniktech.emoji.google.GoogleEmoji.<init>(int[], java.lang.String[], int, int, boolean)' on a null object reference
       at com.vanniktech.emoji.google.category.FlagsCategoryChunk0.get(FlagsCategoryChunk0.java:24)
       at com.vanniktech.emoji.google.category.FlagsCategory.<clinit>(FlagsCategory.java:28)
       at com.vanniktech.emoji.google.GoogleEmojiProvider.getCategories(GoogleEmojiProvider.java:34)
       at com.vanniktech.emoji.EmojiManager.install(EmojiManager.java:105)

**Comment by vanniktech** [comment]
Hmm interesting. Do you have steps how to reproduce this issue?

**Comment by nitishRakuten** [comment]
> Hmm interesting. Do you have steps how to reproduce this issue?

Nope, Found this issue in production build via Crashlytics.

**Comment by vanniktech** [comment]
I'm closing this issue due to inactivity. If you have any further input on the issue, don't hesitate to reopen this issue or post a new one.
