### ISSUE TITLE
Anr issue while getting categories 

### ISSUE THREAD

**Issue by rohitlien** [vanniktech/Emoji#542]
main (runnable): tid=1 systid=16229
       at java.lang.Character.toChars(Character.java:5172)
       at java.lang.StringFactory.newStringFromCodePoints(StringFactory.java:288)
       at com.vanniktech.emoji.emoji.Emoji.<init>(Emoji.java:64)
       at com.vanniktech.emoji.emoji.Emoji.<init>(Emoji.java:58)
       at com.vanniktech.emoji.emoji.Emoji.<init>(Emoji.java:52)
       at com.vanniktech.emoji.google.GoogleEmoji.<init>(GoogleEmoji.java:64)
       at com.vanniktech.emoji.google.category.AnimalsAndNatureCategoryChunk0.get(AnimalsAndNatureCategoryChunk0.java:24)
       at com.vanniktech.emoji.google.category.AnimalsAndNatureCategory.<clinit>(AnimalsAndNatureCategory.java:28)
       at com.vanniktech.emoji.google.GoogleEmojiProvider.getCategories(GoogleEmojiProvider.java:34)
       at com.vanniktech.emoji.EmojiManager.install(EmojiManager.java:105)
       at app.geochat.revamp.application.Trell.onCreate(Trell.java:502)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7523)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7462)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2148)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8528)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by mohitrajput-trell** [comment]
I am also facing this ANR issue. Mostly in Samsung Android 11 devices.

**Comment by vanniktech** [comment]
I don't think there's much we can do here as its a static variable
